indian_airports = {
 "Ahmedabad": "AMD",
    "Bangalore": "BLR",
    "Chennai": "MAA",
    "Delhi": "DEL",
    "Hyderabad": "HYD",
    "Kolkata": "CCU",
    "Mumbai": "BOM",
    "Pune": "PNQ",
    "Jaipur": "JAI",
    "Lucknow": "LKO",
    "Kochi": "COK",
    "Goa": "GOI",
    "Surat": "STV",
    "Coimbatore": "CJB",
    "Nagpur": "NAG",
    "Bhopal": "BHO",
    "Vadodara": "BDQ",
    "Indore": "IDR",
    "Visakhapatnam": "VTZ",
    "Patna": "PAT",
    "Srinagar": "SXR",
    "Mangaluru": "IXE",
    "Dehradun": "DED",
    "Bhubaneswar": "BBI",
    "Raipur": "RPR",
    "Varanasi": "VNS",
    "Amritsar": "ATQ",
    "Jodhpur": "JDH",
    "Gwalior": "GWL",
    "Udaipur": "UDR",
    "Agra": "AGR",
    "Ranchi": "IXR",
    "Shillong": "SHL",
    "Aurangabad": "IXU",
    "Dibrugarh": "DIB",
    "Imphal": "IMF",
    "Jorhat": "JRH",
    "Dimapur": "DMR",
    "Port Blair": "IXZ",
    "Kozhikode": "CCJ",
    "Guwahati": "GAU",
    "Tirupati": "TIR",
    "Mysuru": "MYQ",
    "Patiala": "PTU",
    "Bhatinda": "BUP",
    "Kullu": "KUU",
    "Jammu": "IXJ",
    "Leh": "IXL",
    "Aizawl": "AJL",
    "Agartala": "IXA",
    "Kangra": "DHM",
    "Jaisalmer": "JSA",
    "Diu": "DIU",
    "Puducherry": "PNY",
    "Bikaner": "BKB",
    "Siliguri": "IXB",
    "Silchar": "ICM",
    "Vijayawada": "VGA",
    "Bhuj": "BHJ",
    "Bhavnagar": "BHU",
    "Rajkot": "RAJ",
    "Nashik": "ISK",
    "Kota": "KTU",
}
city=["Ahmedabad", "Bangalore", "Chennai", "Delhi", "Hyderabad",
    "Kolkata", "Mumbai", "Pune", "Jaipur", "Lucknow",
    "Kochi", "Goa", "Surat", "Coimbatore", "Nagpur",
    "Bhopal", "Vadodara", "Indore", "Visakhapatnam", "Patna",
    "Srinagar", "Mangaluru", "Dehradun", "Bhubaneswar", "Raipur",
    "Varanasi", "Amritsar", "Jodhpur", "Gwalior", "Udaipur",
    "Agra", "Ranchi", "Shillong", "Aurangabad", "Dibrugarh",
    "Imphal", "Jorhat", "Dimapur", "Port Blair", "Kozhikode",
    "Guwahati", "Tirupati", "Mysuru", "Patiala", "Bhatinda",
    "Kullu", "Jammu", "Leh", "Aizawl", "Agartala",
    "Kangra", "Jaisalmer", "Diu", "Puducherry", "Bikaner",
    "Siliguri", "Silchar", "Vijayawada", "Bhuj", "Bhavnagar",
    "Rajkot", "Nashik", "Kota"]

# Example usage
city_name = "Mumbai"
airport_code = indian_airports.get(city_name, "City not found")
print(f"The IATA code for {city_name} is {airport_code}.")
print(len(city))

